kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  commands:
  - pip install poetry
  - poetry install
  - poetry run pytest --flake8 --cov=aiger_dfa
  - CODECOV_TOKEN="1f3eb804-cfe8-4f87-9e04-efcd3f9739e7" poetry run codecov